name: Build and push to Azure Container Registry

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Yeet the code to Container
        uses: actions/checkout@v4

      - name: Azure CLI Login for Service Principle
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: ACR Login
        run: az acr login --name acrprincepipelinejune2026

      - name: Docker build and push
        run: |
          docker build -t acrprincepipelinejune2026.azurecr.io/serve-and-log-application:${{ github.sha }} .
          docker push acrprincepipelinejune2026.azurecr.io/serve-and-log-application:${{ github.sha }}